# Generated by Django 3.2.16 on 2022-11-20 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='No title', max_length=200),
            preserve_default=False,
        ),
    ]
